"""Compiling an Analysis into engine SQL.

The compiler translates a fixed vocabulary - normalise, join, window,
aggregate - onto an engine that already knows how to execute queries. It is
deliberately not a query language, and the places it refuses to do something
are as important as the places it does.

Compilation is deterministic: the same Analysis produces the same artifact,
byte for byte, whenever it runs. That is what makes an artifact hash a usable
identity in provenance.
"""

from __future__ import annotations

from datetime import UTC, datetime

from gantry.analysis.artifact import (
    ArtifactLanguage,
    CompilationError,
    GeneratedArtifact,
    UnknownSignalError,
)
from gantry.analysis.model import Analysis, ExecutionEngine, Join, TemporalJoinStrategy
from gantry.analysis.signals import known_signals, signal
from gantry.core.dataset import DatasetManifest
from gantry.verification.sql import qualified, quote

_INDENT = "  "


def resolve_engine(analysis: Analysis, manifests: dict[str, DatasetManifest]) -> ExecutionEngine:
    """Decide which engine runs an Analysis.

    `auto` resolves from where the data actually lives. An Analysis whose
    inputs span engines cannot be compiled as one query, and saying so is
    better than picking one and reading the rest wrongly.
    """
    if analysis.engine is not ExecutionEngine.AUTO:
        return analysis.engine

    adapters = {manifests[name].physical.adapter for name in analysis.inputs if name in manifests}
    if not adapters:
        raise CompilationError(
            analysis.name,
            "no manifests for the declared inputs",
            hint="discover the sources before compiling",
        )
    if len(adapters) > 1:
        raise CompilationError(
            analysis.name,
            f"inputs span more than one engine: {', '.join(sorted(adapters))}",
            hint="v1 compiles an Analysis onto a single engine",
        )

    adapter = adapters.pop()
    try:
        return ExecutionEngine(adapter)
    except ValueError as error:
        raise CompilationError(
            analysis.name,
            f"no engine for adapter {adapter!r}",
            hint=f"supported: {', '.join(e.value for e in ExecutionEngine)}",
        ) from error


def compile_analysis(
    analysis: Analysis,
    manifests: dict[str, DatasetManifest],
    *,
    engine: ExecutionEngine | None = None,
    generated_at: datetime | None = None,
) -> GeneratedArtifact:
    """Compile an Analysis into an executable artifact."""
    chosen = engine or resolve_engine(analysis, manifests)
    _check_inputs(analysis, manifests)

    normalised = _normalisation_ctes(analysis, manifests)
    joined = _join_expression(analysis, manifests)
    projection = _projection(analysis, manifests)

    body = "\n".join(
        (
            "-- Generated by Gantry. Do not edit: this artifact is provenance,",
            "-- and its hash identifies the Result it produced.",
            f"-- analysis: {analysis.name}",
            f"-- engine:   {chosen.value}",
            "WITH " + ",\n".join(normalised) if normalised else "",
            f"SELECT{projection}",
            f"FROM {joined}",
            _group_by(analysis, manifests),
        )
    ).strip()

    return GeneratedArtifact(
        analysis=analysis.name,
        engine=chosen.value,
        language=ArtifactLanguage.SQL,
        body=_tidy(body),
        inputs=analysis.inputs,
        parameters=_parameters(analysis),
        generated_at=generated_at or datetime.now(UTC),
    )


def compile_relation(analysis: Analysis, manifests: dict[str, DatasetManifest]) -> tuple[str, str]:
    """The normalised inputs and the joined relation, without aggregation.

    Verification measures the join, not the aggregate. A join that multiplies
    its left side is invisible once the rows have been grouped away, so the
    checks that catch it have to see the same relation the aggregate was
    computed over - built by the same code, not a reimplementation that might
    disagree.
    """
    _check_inputs(analysis, manifests)
    ctes = _normalisation_ctes(analysis, manifests)
    prefix = "WITH " + ",\n".join(ctes) if ctes else ""
    return prefix, _join_expression(analysis, manifests)


def left_input(analysis: Analysis) -> str:
    """The input a join expands from."""
    return analysis.inputs[0]


def qualified_column(analysis: Analysis, manifests: dict[str, DatasetManifest], column: str) -> str:
    """A column reference valid inside the joined relation."""
    return _qualify(_column_owners(analysis, manifests), column)


def relation_alias(dataset: str) -> str:
    return _alias(dataset)


def normalised_name(dataset: str) -> str:
    return _cte_name(dataset)


def _check_inputs(analysis: Analysis, manifests: dict[str, DatasetManifest]) -> None:
    missing = [name for name in analysis.inputs if name not in manifests]
    if missing:
        raise CompilationError(
            analysis.name,
            f"no manifest for inputs: {', '.join(missing)}",
            hint="discover the sources before compiling",
        )


def _normalisation_ctes(analysis: Analysis, manifests: dict[str, DatasetManifest]) -> list[str]:
    """One CTE per input, renaming aliases onto canonical names.

    Normalisation happens before anything joins, so a join condition names one
    column rather than a disjunction of whatever each source happened to call
    it.
    """
    aliases = {alias: item.canonical for item in analysis.normalize for alias in item.aliases}

    ctes: list[str] = []
    for name in analysis.inputs:
        manifest = manifests[name]
        columns: list[str] = []
        for field in manifest.dataset_schema.fields:
            canonical = aliases.get(field.name, field.name)
            columns.append(
                f"{quote(field.name)} AS {quote(canonical)}"
                if canonical != field.name
                else quote(field.name)
            )
        where = _window_predicate(analysis, manifest)
        ctes.append(
            f"{quote(_cte_name(name))} AS (\n"
            f"{_INDENT}SELECT {', '.join(columns)}\n"
            f"{_INDENT}FROM {qualified(manifest.physical.reference)}"
            + (f"\n{_INDENT}WHERE {where}" if where else "")
            + "\n)"
        )
    return ctes


def _window_predicate(analysis: Analysis, manifest: DatasetManifest) -> str | None:
    """Restrict an input to the Analysis window, where it has a time field.

    Applied per input rather than after the join, so the engine can use an
    index and the join sees only rows that can contribute.
    """
    if analysis.window is None:
        return None
    time_field = manifest.dataset_schema.time_field
    if time_field is None:
        return None
    return (
        f"{quote(time_field)} >= TIMESTAMPTZ '{analysis.window.start.isoformat()}' "
        f"AND {quote(time_field)} < TIMESTAMPTZ '{analysis.window.end.isoformat()}'"
    )


def _join_expression(analysis: Analysis, manifests: dict[str, DatasetManifest]) -> str:
    """Build the FROM clause, chaining joins left to right."""
    first = analysis.inputs[0]
    expression = f"{quote(_cte_name(first))} AS {quote(_alias(first))}"

    for join in analysis.joins:
        expression += "\n" + (
            _temporal_join(join, manifests) if join.temporal is not None else _equi_join(join)
        )
    return expression


def _equi_join(join: Join) -> str:
    conditions = " AND ".join(
        f"{quote(_alias(join.left))}.{quote(column)} = {quote(_alias(join.right))}.{quote(column)}"
        for column in join.on
    )
    return (
        f"JOIN {quote(_cte_name(join.right))} AS {quote(_alias(join.right))}\n"
        f"{_INDENT}ON {conditions}"
    )


def _temporal_join(join: Join, manifests: dict[str, DatasetManifest]) -> str:
    """A join to the nearest row in time, rather than to an equal one.

    Expressed as a lateral subquery taking one row: a plain join on a time
    comparison would match every candidate within the distance and multiply the
    left side by however many there are, which is the row-expansion failure the
    verification layer exists to catch. Better not to generate it.
    """
    temporal = join.temporal
    if temporal is None:  # pragma: no cover - guarded by the caller
        raise ValueError("not a temporal join")

    right_manifest = manifests[join.right]
    left_manifest = manifests[join.left]
    right_time = right_manifest.dataset_schema.time_field
    left_time = left_manifest.dataset_schema.time_field
    if right_time is None or left_time is None:
        raise CompilationError(
            join.right,
            f"temporal join between {join.left!r} and {join.right!r} needs a time field on both",
            hint="declare semantics.timeField on each Dataset",
        )

    left_alias = quote(_alias(join.left))
    right_alias = quote(_alias(join.right))
    equality = " AND ".join(
        f"{right_alias}.{quote(column)} = {left_alias}.{quote(column)}" for column in join.on
    )

    comparison, ordering = {
        TemporalJoinStrategy.NEAREST_PRECEDING: ("<=", "DESC"),
        TemporalJoinStrategy.NEAREST_FOLLOWING: (">=", "ASC"),
        TemporalJoinStrategy.NEAREST: ("IS NOT NULL AND TRUE OR", "ASC"),
    }[temporal.strategy]

    if temporal.strategy is TemporalJoinStrategy.NEAREST:
        raise CompilationError(
            join.right,
            "temporal strategy 'nearest' is not supported in v1",
            hint="use nearest_preceding or nearest_following",
        )

    bound = ""
    if temporal.max_distance_seconds is not None:
        direction = "-" if temporal.strategy is TemporalJoinStrategy.NEAREST_PRECEDING else "+"
        bound = (
            f"\n{_INDENT * 3}AND {right_alias}.{quote(right_time)} "
            f"{'>=' if direction == '-' else '<='} "
            f"{left_alias}.{quote(left_time)} {direction} "
            f"INTERVAL '{temporal.max_distance_seconds} seconds'"
        )

    return (
        f"LEFT JOIN LATERAL (\n"
        f"{_INDENT * 2}SELECT *\n"
        f"{_INDENT * 2}FROM {quote(_cte_name(join.right))} AS {right_alias}\n"
        f"{_INDENT * 2}WHERE {equality}\n"
        f"{_INDENT * 3}AND {right_alias}.{quote(right_time)} {comparison} "
        f"{left_alias}.{quote(left_time)}{bound}\n"
        f"{_INDENT * 2}ORDER BY {right_alias}.{quote(right_time)} {ordering}\n"
        f"{_INDENT * 2}LIMIT 1\n"
        f"{_INDENT}) AS {right_alias} ON TRUE"
    )


def _projection(analysis: Analysis, manifests: dict[str, DatasetManifest]) -> str:
    """The grouped columns and the requested signals."""
    owners = _column_owners(analysis, manifests)
    parts = [
        f"\n{_INDENT}{_qualify(owners, column)} AS {quote(column)}"
        for column in _grouping_columns(analysis)
    ]

    for name in analysis.signals:
        definition = signal(name)
        if definition is None:
            raise UnknownSignalError(analysis.name, name, known_signals())
        missing = [column for column in definition.requires if column not in owners]
        if missing:
            raise CompilationError(
                analysis.name,
                f"signal {name!r} needs columns the inputs do not provide: {', '.join(missing)}",
                hint="normalise an input field onto that name, or drop the signal",
            )
        expression = definition.expression.format(
            **{column: _qualify(owners, column) for column in definition.requires}
        )
        parts.append(f"\n{_INDENT}{expression} AS {quote(name)}")

    if not parts:
        raise CompilationError(
            analysis.name,
            "nothing to select",
            hint="declare at least one signal",
        )
    return ",".join(parts)


def _column_owners(analysis: Analysis, manifests: dict[str, DatasetManifest]) -> dict[str, str]:
    """Which input each column should be read from.

    Normalising two fields onto one name puts that column on both sides, so an
    unqualified reference is ambiguous - and the point of normalising is that
    the values agree, so which side answers does not matter. The leftmost input
    wins, deterministically.
    """
    aliases = {alias: item.canonical for item in analysis.normalize for alias in item.aliases}
    owners: dict[str, str] = {}
    for name in analysis.inputs:
        for field in manifests[name].dataset_schema.fields:
            owners.setdefault(aliases.get(field.name, field.name), _alias(name))
    return owners


def _qualify(owners: dict[str, str], column: str) -> str:
    owner = owners.get(column)
    return f"{quote(owner)}.{quote(column)}" if owner else quote(column)


def _grouping_columns(analysis: Analysis) -> tuple[str, ...]:
    """Group by every canonical field the spec normalised.

    Normalising a field is the spec's way of saying it identifies something
    across sources, which is exactly what a grouping key is.
    """
    return tuple(sorted({item.canonical for item in analysis.normalize}))


def _group_by(analysis: Analysis, manifests: dict[str, DatasetManifest]) -> str:
    columns = _grouping_columns(analysis)
    if not columns:
        return ""
    owners = _column_owners(analysis, manifests)
    return "GROUP BY " + ", ".join(_qualify(owners, column) for column in columns)


def _parameters(analysis: Analysis) -> dict[str, str]:
    parameters: dict[str, str] = {}
    if analysis.window is not None:
        parameters["window_start"] = analysis.window.start.isoformat()
        parameters["window_end"] = analysis.window.end.isoformat()
    return parameters


def _cte_name(dataset: str) -> str:
    return "n_" + dataset.replace(".", "_")


def _alias(dataset: str) -> str:
    return dataset.replace(".", "_")


def _tidy(body: str) -> str:
    return "\n".join(line.rstrip() for line in body.splitlines() if line.strip()) + "\n"
