"""task queue

Revision ID: 46cea0882cf4
Revises: b1caba59d8e6
Create Date: 2026-09-04 15:44:16.591286
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "46cea0882cf4"
down_revision: str | None = "b1caba59d8e6"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("operation", sa.String(length=253), nullable=False),
        sa.Column("node_id", sa.String(length=64), nullable=False),
        sa.Column("plan_version", sa.Integer(), nullable=False),
        sa.Column("depends_on", postgresql.ARRAY(sa.String()), server_default="{}", nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("lease_owner", sa.String(length=128), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["operation"], ["operations.name"], name="fk_tasks_operation"),
        sa.PrimaryKeyConstraint("operation", "node_id", name=op.f("pk_tasks")),
    )
    op.create_index("ix_tasks_leasable", "tasks", ["operation", "state"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tasks_leasable", table_name="tasks")
    op.drop_table("tasks")
    # ### end Alembic commands ###
