"""tombstones move to the target

Revision ID: 594e53908f98
Revises: dda39d7f767c
Create Date: 2026-09-04 21:14:35.359073
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "594e53908f98"
down_revision: str | None = "dda39d7f767c"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cdc_tombstones")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cdc_tombstones",
        sa.Column("operation", sa.VARCHAR(length=253), autoincrement=False, nullable=False),
        sa.Column("dataset", sa.VARCHAR(length=253), autoincrement=False, nullable=False),
        sa.Column("key_text", sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
        sa.Column("source_lsn", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "deleted_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["operation"], ["operations.name"], name=op.f("fk_cdc_tombstones_operation")
        ),
        sa.PrimaryKeyConstraint("operation", "dataset", "key_text", name=op.f("pk_cdc_tombstones")),
    )
    # ### end Alembic commands ###
