"""analysis artifacts

Revision ID: 9556321f11ae
Revises: 594e53908f98
Create Date: 2026-09-04 21:56:42.255094
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "9556321f11ae"
down_revision: str | None = "594e53908f98"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysis_artifacts",
        sa.Column("content_hash", sa.String(length=71), nullable=False),
        sa.Column("analysis", sa.String(length=253), nullable=False),
        sa.Column("engine", sa.String(length=32), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("inputs", postgresql.ARRAY(sa.String()), server_default="{}", nullable=False),
        sa.Column(
            "parameters",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("content_hash", name=op.f("pk_analysis_artifacts")),
    )
    op.create_index(
        "ix_analysis_artifacts_analysis",
        "analysis_artifacts",
        ["analysis", "generated_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_analysis_artifacts_analysis", table_name="analysis_artifacts")
    op.drop_table("analysis_artifacts")
    # ### end Alembic commands ###
