"""initial metadata schema

Revision ID: b1caba59d8e6
Revises:
Create Date: 2026-09-04 15:38:29.298910
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "b1caba59d8e6"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("operation", sa.String(length=253), nullable=True),
        sa.Column("actor", sa.String(length=32), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index("ix_audit_log_time", "audit_log", ["occurred_at"], unique=False)
    op.create_table(
        "dataset_versions",
        sa.Column("name", sa.String(length=253), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=71), nullable=False),
        sa.Column("manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("registered_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("version >= 1", name=op.f("ck_dataset_versions_version_positive")),
        sa.PrimaryKeyConstraint("name", "version", name=op.f("pk_dataset_versions")),
        sa.UniqueConstraint("name", "content_hash", name="uq_dataset_versions_content"),
    )
    op.create_table(
        "operations",
        sa.Column("name", sa.String(length=253), nullable=False),
        sa.Column("operation_type", sa.String(length=32), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("current_plan_version", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("row_version", sa.Integer(), server_default="1", nullable=False),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_operations")),
    )
    op.create_table(
        "checkpoints",
        sa.Column("operation", sa.String(length=253), nullable=False),
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("scope_id", sa.String(length=512), nullable=False),
        sa.Column("position_kind", sa.String(length=32), nullable=False),
        sa.Column("position_value", sa.Text(), nullable=False),
        sa.Column("committed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["operation"], ["operations.name"], name="fk_checkpoints_operation"
        ),
        sa.PrimaryKeyConstraint("operation", "scope", "scope_id", name=op.f("pk_checkpoints")),
    )
    op.create_table(
        "plan_versions",
        sa.Column("operation", sa.String(length=253), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=71), nullable=False),
        sa.Column("guarantee_fingerprint", sa.String(length=71), nullable=False),
        sa.Column("plan", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("version >= 1", name=op.f("ck_plan_versions_version_positive")),
        sa.ForeignKeyConstraint(
            ["operation"], ["operations.name"], name="fk_plan_versions_operation"
        ),
        sa.PrimaryKeyConstraint("operation", "version", name=op.f("pk_plan_versions")),
    )
    op.create_table(
        "results",
        sa.Column("name", sa.String(length=253), nullable=False),
        sa.Column("operation", sa.String(length=253), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["operation"], ["operations.name"], name="fk_results_operation"),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_results")),
    )
    op.create_table(
        "state_transitions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("operation", sa.String(length=253), nullable=False),
        sa.Column("from_state", sa.String(length=32), nullable=False),
        sa.Column("to_state", sa.String(length=32), nullable=False),
        sa.Column("actor", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("plan_version", sa.Integer(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "length(btrim(reason)) > 0", name=op.f("ck_state_transitions_reason_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["operation"], ["operations.name"], name="fk_state_transitions_operation"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_state_transitions")),
    )
    op.create_index(
        "ix_state_transitions_operation_time",
        "state_transitions",
        ["operation", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "verification_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("operation", sa.String(length=253), nullable=False),
        sa.Column("plan_version", sa.Integer(), nullable=False),
        sa.Column("check_name", sa.String(length=64), nullable=False),
        sa.Column("scope", sa.String(length=512), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=32), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["operation"], ["operations.name"], name="fk_verification_results_operation"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verification_results")),
    )
    op.create_index(
        "ix_verification_results_operation",
        "verification_results",
        ["operation", "plan_version"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_verification_results_operation", table_name="verification_results")
    op.drop_table("verification_results")
    op.drop_index("ix_state_transitions_operation_time", table_name="state_transitions")
    op.drop_table("state_transitions")
    op.drop_table("results")
    op.drop_table("plan_versions")
    op.drop_table("checkpoints")
    op.drop_table("operations")
    op.drop_table("dataset_versions")
    op.drop_index("ix_audit_log_time", table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
