"""cdc tombstones and dead letters

Revision ID: dda39d7f767c
Revises: 04a851ba4ed9
Create Date: 2026-09-04 21:11:32.484577
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "dda39d7f767c"
down_revision: str | None = "04a851ba4ed9"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cdc_tombstones",
        sa.Column("operation", sa.String(length=253), nullable=False),
        sa.Column("dataset", sa.String(length=253), nullable=False),
        sa.Column("key_text", sa.String(length=1024), nullable=False),
        sa.Column("source_lsn", sa.BigInteger(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["operation"], ["operations.name"], name="fk_cdc_tombstones_operation"
        ),
        sa.PrimaryKeyConstraint("operation", "dataset", "key_text", name=op.f("pk_cdc_tombstones")),
    )
    op.create_table(
        "dead_letters",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("operation", sa.String(length=253), nullable=False),
        sa.Column("dataset", sa.String(length=253), nullable=False),
        sa.Column("key_text", sa.String(length=1024), nullable=True),
        sa.Column("source_lsn", sa.BigInteger(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("replayed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["operation"], ["operations.name"], name="fk_dead_letters_operation"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dead_letters")),
    )
    op.create_index(
        "ix_dead_letters_pending", "dead_letters", ["operation", "replayed_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_dead_letters_pending", table_name="dead_letters")
    op.drop_table("dead_letters")
    op.drop_table("cdc_tombstones")
    # ### end Alembic commands ###
