# SPDX-License-Identifier: Apache-2.0
"""Verifying an Iceberg table.

A PostgreSQL target computes its own checksum, because there is an engine to
send SQL to. An Iceberg table is a set of Parquet files and a metadata tree, and
the alternative to running a job here would be streaming every row into the
Gantry process to add it up — which is precisely what this project exists not to
do. So the checksum is computed by a job, in a container, and what comes back is
one number and one count.

The job runs `gantry.verification.portable`, the same code the rest of the
system uses, rather than a normalisation inlined into a generated script. One
definition, two implementations (SQL and Python) is already a standing hazard;
three would be untenable.
"""

from __future__ import annotations

import json
import re
from datetime import UTC, datetime

from gantry.core import DatasetManifest
from gantry.core.names import ResourceName
from gantry.jobs.model import Job, JobKind
from gantry.jobs.packaging import Packaging
from gantry.verification.checksum import ChunkChecksum

CHECKSUM_MARKER = "gantry-checksum"
_RESULT = re.compile(rf"^{CHECKSUM_MARKER} (\S+) (\d+)$", re.MULTILINE)


class IcebergVerificationError(Exception):
    """The verification job produced nothing a checksum could be read from."""


def checksum_script(
    manifest: DatasetManifest,
    *,
    warehouse: str,
    table: str,
    predicate: str | None = None,
) -> str:
    """A program that reads an Iceberg table and prints one checksum.

    `predicate` is a pyiceberg row filter, so a group can be verified without
    reading the whole table. Left out, the whole table is summed.

    The manifest travels as JSON rather than being rediscovered inside the job:
    the checksum's definition depends on the declared column types, and a job
    that looked them up itself could disagree with the side it is being compared
    against.
    """
    return f'''#!/usr/bin/env python
"""Generated by Gantry: the checksum of an Iceberg table.

Retained as provenance. Reads Parquet, prints one number and one count, and
sends no rows anywhere.
"""

import glob
import json
import os
import sys

from pyiceberg.table import StaticTable

from gantry.core import DatasetManifest
from gantry.verification.portable import checksum

WAREHOUSE = {warehouse!r}
TABLE = {table!r}
PREDICATE = {predicate!r}
MANIFEST = {json.dumps(manifest.model_dump(mode="json"))!r}


def main() -> int:
    namespace, _, name = TABLE.rpartition(".")
    root = os.path.join(WAREHOUSE, namespace.replace(".", "/"), name, "metadata")
    versions = sorted(glob.glob(os.path.join(root, "v*.metadata.json")))
    if not versions:
        print(f"no Iceberg metadata under {{root}}", file=sys.stderr)
        return 1

    table = StaticTable.from_metadata(versions[-1])
    scan = table.scan(row_filter=PREDICATE) if PREDICATE else table.scan()

    manifest = DatasetManifest.model_validate(json.loads(MANIFEST))
    result = checksum(manifest, scan.to_arrow().to_pylist())
    print(f"{CHECKSUM_MARKER} {{result.checksum}} {{result.rows}}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def compile_checksum_job(
    operation: ResourceName,
    manifest: DatasetManifest,
    *,
    warehouse: str,
    table: str,
    packaging: Packaging,
    unit: str,
    predicate: str | None = None,
    generated_at: datetime | None = None,
) -> Job:
    """The verification of one unit, as a job."""
    return Job(
        operation=operation,
        kind=JobKind.SQL,
        unit=unit,
        body=checksum_script(manifest, warehouse=warehouse, table=table, predicate=predicate),
        packaging=packaging,
        generated_at=generated_at or datetime.now(UTC),
    )


def parse_checksum(output: str) -> ChunkChecksum:
    """Read the job's answer.

    A missing marker is an error rather than an empty result: a checksum of zero
    over zero rows is what an empty table legitimately reports, so it must never
    also be what a job that failed to run reports.
    """
    found = _RESULT.search(output)
    if found is None:
        raise IcebergVerificationError(
            f"no {CHECKSUM_MARKER!r} line in the verification job's output"
        )
    return ChunkChecksum(checksum=found.group(1), rows=int(found.group(2)))
