# SPDX-License-Identifier: Apache-2.0
"""Compiling a partition into an Apache Beam job.

The same contract as `gantry.movement.sqljob`, and deliberately so: Gantry
decides the partition bounds, the target, and what "committed" means, and hands
the rest to something else. What differs is only what the something else is.

Three things about Beam shape this module, all of them measured rather than
assumed (see `docs/benchmarks.md`):

- `apache_beam.io.jdbc` is a **cross-language transform**. The Python API is a
  facade over a Java expansion service, so the job's image carries a JRE and
  pre-staged JARs. That is the packaging's problem, and nothing here names it.
- Beam's own JDBC write is an `INSERT`, which a replay would duplicate. The
  upsert is passed explicitly as `statement=`, because idempotence is Gantry's
  guarantee and not something to be inherited by luck.
- A Beam job costs seconds to start, against fractions of one for a SQL script.
  The unit is therefore allowed to be several partitions, and the checkpoint
  granularity that follows is what the guarantee table has to report.
"""

from __future__ import annotations

from collections.abc import Sequence
from datetime import UTC, datetime

from gantry.adapters.target.postgres import SNAPSHOT_LSN_COLUMN
from gantry.core.dataset import DatasetManifest
from gantry.core.names import ResourceName
from gantry.jobs.model import Job, JobKind
from gantry.jobs.packaging import Packaging
from gantry.movement.partitioning import Partition
from gantry.movement.predicate import bounds
from gantry.verification.sql import qualified, quote

# Connection details are secrets. They reach the running job by name through the
# packaging and never appear in the body, which is retained and meant to be read.
SOURCE_JDBC = "GANTRY_SOURCE_JDBC"
TARGET_JDBC = "GANTRY_TARGET_JDBC"
SOURCE_USER = "GANTRY_SOURCE_USER"
SOURCE_PASSWORD = "GANTRY_SOURCE_PASSWORD"
TARGET_USER = "GANTRY_TARGET_USER"
TARGET_PASSWORD = "GANTRY_TARGET_PASSWORD"

JDBC_SECRETS = (
    SOURCE_JDBC,
    TARGET_JDBC,
    SOURCE_USER,
    SOURCE_PASSWORD,
    TARGET_USER,
    TARGET_PASSWORD,
)

DRIVER = "org.postgresql.Driver"
COMMIT_MARKER = "gantry-commit"


def snapshot_pipeline(
    manifest: DatasetManifest,
    partitions: Sequence[Partition],
    *,
    target: str,
    snapshot_lsn: int | None = None,
) -> str:
    """The pipeline, as a Python program.

    Retained as provenance and meant to be read by a person: an operator will
    eventually run one of these by hand to work out what happened.
    """
    if not partitions:
        raise ValueError("a job must cover at least one partition")

    schema = manifest.dataset_schema
    names = [field.name for field in schema.fields]
    predicate = " OR ".join(f"({bounds(manifest, part)})" for part in partitions)
    projection = _projection(manifest, names, snapshot_lsn=snapshot_lsn)
    query = f"SELECT {projection} FROM {qualified(manifest.name)} WHERE {predicate}"
    upsert = _upsert(target, names, list(schema.keys), snapshot_lsn=snapshot_lsn)

    return f'''#!/usr/bin/env python
"""Generated by Gantry for {manifest.name}, {len(partitions)} partition(s).

Retained as provenance: this is exactly what moved the rows. The bounds come
from the plan and are never recomputed here — recomputing them would let a
partition move under a replay.
"""

import os
import sys

import apache_beam as beam
from apache_beam.io.jdbc import ReadFromJdbc, WriteToJdbc
from apache_beam.options.pipeline_options import PipelineOptions

QUERY = {query!r}

# An explicit upsert. Beam's JDBC write is an INSERT, which a replay would
# duplicate; idempotence is Gantry's guarantee, not one to inherit by luck.
UPSERT = {upsert!r}


def main() -> int:
    options = PipelineOptions(sys.argv[1:] or ["--runner=DirectRunner"])
    with beam.Pipeline(options=options) as pipeline:
        (
            pipeline
            | "read"
            >> ReadFromJdbc(
                table_name={_table_of(manifest.name)!r},
                driver_class_name={DRIVER!r},
                jdbc_url=os.environ[{SOURCE_JDBC!r}],
                username=os.environ[{SOURCE_USER!r}],
                password=os.environ[{SOURCE_PASSWORD!r}],
                query=QUERY,
            )
            | "write"
            >> WriteToJdbc(
                table_name={_table_of(target)!r},
                driver_class_name={DRIVER!r},
                jdbc_url=os.environ[{TARGET_JDBC!r}],
                username=os.environ[{TARGET_USER!r}],
                password=os.environ[{TARGET_PASSWORD!r}],
                statement=UPSERT,
            )
        )

    # Beam reports no per-row counts a submitter can read, so this says only
    # what it can honestly say: the pipeline reached DONE, which means committed
    # and not correct. Nothing is checkpointed on it alone — the group is
    # verified first.
    print("{COMMIT_MARKER} done")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def compile_snapshot_job(
    operation: ResourceName,
    manifest: DatasetManifest,
    partitions: Sequence[Partition],
    *,
    target: str,
    packaging: Packaging,
    snapshot_lsn: int | None = None,
    generated_at: datetime | None = None,
) -> Job:
    """One unit of Beam work, ready to hand to any runner.

    The unit may be several partitions, because Beam's startup cost makes one
    job per partition unaffordable. Which partitions travel together is the
    plan's decision, not this function's.
    """
    return Job(
        operation=operation,
        kind=JobKind.BEAM,
        unit=unit_of(partitions),
        body=snapshot_pipeline(manifest, partitions, target=target, snapshot_lsn=snapshot_lsn),
        packaging=packaging,
        generated_at=generated_at or datetime.now(UTC),
    )


def unit_of(partitions: Sequence[Partition]) -> str:
    """What a job covers, as one stable string.

    Sorted, so that the same set of partitions is the same unit however the plan
    happened to order them — otherwise a replay would compile to a different job
    and the runner would not recognise it.
    """
    return ",".join(sorted(part.id for part in partitions))


def _projection(
    manifest: DatasetManifest, names: Sequence[str], *, snapshot_lsn: int | None
) -> str:
    """Columns to read, with the snapshot position stamped on if there is one.

    Stamped in the *source* query rather than in the write, because Beam moves
    rows opaquely between the two and there is no later point that still knows
    what the position was.
    """
    if snapshot_lsn is None:
        return ", ".join(quote(name) for name in names)
    return ", ".join(
        f"CAST({int(snapshot_lsn)} AS bigint) AS {quote(name)}"
        if name == SNAPSHOT_LSN_COLUMN
        else quote(name)
        for name in names
    )


def _upsert(
    target: str, names: Sequence[str], keys: Sequence[str], *, snapshot_lsn: int | None
) -> str:
    """The write statement, with a placeholder per column in schema order.

    When a snapshot position is given the write refuses to overwrite anything
    newer. That guard is load-bearing here in a way it is not for a SQL script:
    a Beam pipeline's bundles are unordered by design and may be retried, so
    "the snapshot wrote it second" carries no information about which value is
    current. Without it a partition copied slowly enough silently undoes changes
    the stream already applied, and the row looks consistent afterwards.
    """
    columns = ", ".join(quote(name) for name in names)
    placeholders = ", ".join("?" for _ in names)
    key_columns = ", ".join(quote(key) for key in keys)
    updatable = [name for name in names if name not in set(keys)]
    statement = (
        f"INSERT INTO {qualified(target)} ({columns}) VALUES ({placeholders}) "
        f"ON CONFLICT ({key_columns}) "
    )
    if not updatable:
        # A table that is all key has nothing to update; a conflict means the
        # row is already exactly right.
        return statement + "DO NOTHING"
    assignments = ", ".join(f"{quote(name)} = EXCLUDED.{quote(name)}" for name in updatable)
    statement += f"DO UPDATE SET {assignments}"
    if snapshot_lsn is None:
        return statement
    # Compared against the stamped value rather than a literal, so the guard and
    # the stamp in the read cannot drift apart.
    lsn = quote(SNAPSHOT_LSN_COLUMN)
    return f"{statement} WHERE {qualified(target)}.{lsn} < EXCLUDED.{lsn}"


def _table_of(reference: str) -> str:
    """JdbcIO wants a bare table name alongside the query it will actually run."""
    return reference.split(".")[-1]
