# SPDX-License-Identifier: Apache-2.0
"""Compiling a partition copy into a SQL job.

The default job kind. A shell script that pipes one `COPY` into another and
merges from staging — the same shape the v1 relay had, except that it runs
somewhere disposable instead of inside the Gantry worker.

Three details here are Day 0 findings, and **all three are silent when wrong**:

- `COPY … FROM STDIN` is passed with `-c`, never inside a `-f` script. In a
  script file psql reads the COPY data from the file itself rather than from
  stdin, and the obvious formulation fails with "COPY file signature not
  recognized".
- `set -o pipefail`, so a source-side failure cannot be hidden by a target
  stage that exited cleanly. Today a truncated binary `COPY` stream is rejected
  anyway because the format has a trailer — but that is a property of the wire
  format, and a job whose correctness depends on the format rather than on its
  own exit handling is one format change from silently succeeding.
- `--single-transaction` with `ON_ERROR_STOP=1`, which is what makes **exit 0
  mean committed**.

The script is meant to be read. It is retained as provenance, and an operator
will eventually run one by hand to work out what happened.
"""

from __future__ import annotations

import re
from collections.abc import Sequence
from datetime import UTC, datetime

from gantry.core.commit import CommitResult
from gantry.core.dataset import DatasetManifest
from gantry.core.names import ResourceName
from gantry.jobs.model import Job, JobKind
from gantry.jobs.packaging import Packaging, sql_client_packaging
from gantry.movement.partitioning import Partition
from gantry.verification.sql import column_type, qualified, quote

# Connection strings are secrets. They reach the running job by name through the
# packaging, and never appear in the body — which is retained and readable.
SOURCE_DSN = "GANTRY_SOURCE_DSN"
TARGET_DSN = "GANTRY_TARGET_DSN"


# Control characters have no business in a key bound and would let a value break
# out of the line it is written on. Rejected rather than escaped: a bound that
# needs escaping this badly is a bug upstream.
_FORBIDDEN = re.compile(r"[\x00-\x1f\x7f]")


def sql_literal(value: str) -> str:
    """A single-quoted SQL literal.

    Doubling the quote is sufficient because PostgreSQL has had
    `standard_conforming_strings` on by default since 9.1, so a backslash is
    just a backslash. Control characters are refused outright.
    """
    if _FORBIDDEN.search(value):
        raise ValueError(f"control characters in a key bound: {value!r}")
    return "'" + value.replace("'", "''") + "'"


def shell_literal(value: str) -> str:
    """A single-quoted shell word.

    The SQL is nested inside a shell script, so it is escaped twice. This is
    the outer layer, and the reason `sql_literal` refuses control characters is
    that they would survive it.
    """
    return "'" + value.replace("'", "'\\''") + "'"


def snapshot_script(
    manifest: DatasetManifest,
    partition: Partition,
    *,
    target: str,
    snapshot_lsn: int | None = None,
) -> str:
    """The shell script that copies one partition.

    Bounds come from the plan rather than being recomputed. Recomputing them at
    execution time would let a partition move under a replay, which would make
    its checkpoint refer to work that no longer exists.
    """
    names = [field.name for field in manifest.dataset_schema.fields]
    if not names:
        raise ValueError(f"dataset {manifest.name!r} has no discovered fields")
    keys = list(manifest.dataset_schema.keys)
    if not keys:
        raise ValueError(f"dataset {manifest.name!r} has no key; idempotent writes need one")

    columns = ", ".join(quote(name) for name in names)
    source_table = qualified(manifest.physical.reference)
    target_table = qualified(target)
    predicate = _bounds(manifest, partition)

    read = (
        f"COPY (SELECT {columns} FROM {source_table} WHERE {predicate}) TO STDOUT (FORMAT binary)"
    )
    stage = f"CREATE TEMP TABLE gantry_staging (LIKE {target_table}) ON COMMIT DROP"
    load = f"COPY gantry_staging ({columns}) FROM STDIN (FORMAT binary)"
    merge = _merge(target_table, names, keys, snapshot_lsn=snapshot_lsn)

    return "\n".join(
        (
            "#!/bin/sh",
            f"# Generated by Gantry for {manifest.name} partition {partition.id}.",
            "# Retained as provenance: this is exactly what moved the rows.",
            "set -eu",
            "# Without pipefail a source-side failure is masked by a target",
            "# stage that exited cleanly.",
            "set -o pipefail",
            "",
            f'psql "${SOURCE_DSN}" -v ON_ERROR_STOP=1 \\',
            f"  -c {shell_literal(read)} \\",
            f'| psql "${TARGET_DSN}" -v ON_ERROR_STOP=1 --single-transaction -tA \\',
            f"  -c {shell_literal(stage)} \\",
            f"  -c {shell_literal(load)} \\",
            f"  -c {shell_literal(merge)}",
        )
    )


def compile_snapshot_job(
    operation: ResourceName,
    manifest: DatasetManifest,
    partition: Partition,
    *,
    target: str,
    packaging: Packaging | None = None,
    snapshot_lsn: int | None = None,
    generated_at: datetime | None = None,
) -> Job:
    """One partition, as a job ready to hand to any runner.

    `packaging` says how the script is made runnable. It is deliberately the
    abstract type: this function writes SQL and must not know what a container
    is. The default is the SQL client packaging, which is a convenience, not an
    assumption baked into the generator.
    """
    return Job(
        operation=operation,
        kind=JobKind.SQL,
        unit=partition.id,
        body=snapshot_script(manifest, partition, target=target, snapshot_lsn=snapshot_lsn),
        packaging=packaging or sql_client_packaging(secrets=(SOURCE_DSN, TARGET_DSN)),
        generated_at=generated_at or datetime.now(UTC),
    )


def _bounds(manifest: DatasetManifest, partition: Partition) -> str:
    """The partition predicate, with bounds re-typed from the schema.

    Bounds travel as text so the runtime need not know whether a key is a
    bigint or a uuid; the cast puts the type back on at the point of use.
    """
    column = quote(partition.column)
    declared = column_type(manifest, partition.column)
    clauses: list[str] = []
    if partition.lo is not None:
        clauses.append(f"{column} >= CAST({sql_literal(partition.lo)} AS {declared})")
    if partition.hi is not None:
        clauses.append(f"{column} < CAST({sql_literal(partition.hi)} AS {declared})")
    return " AND ".join(clauses) if clauses else "TRUE"


def _merge(
    target: str, names: Sequence[str], keys: Sequence[str], *, snapshot_lsn: int | None
) -> str:
    """Upsert staged rows into the target.

    When a snapshot position is given the merge refuses to overwrite anything
    newer, which is what makes a snapshot and a change stream safe to run at the
    same time: a partition copied slowly enough would otherwise silently undo
    changes the stream had already applied, and the row would look consistent
    afterwards.
    """
    columns = ", ".join(quote(name) for name in names)
    key_columns = ", ".join(quote(key) for key in keys)
    updatable = [name for name in names if name not in set(keys)]
    if not updatable:
        # A table that is all key has nothing to update; a conflict means the
        # row is already exactly right.
        return _counted(
            f"INSERT INTO {target} ({columns}) SELECT {columns} FROM gantry_staging "
            f"ON CONFLICT ({key_columns}) DO NOTHING"
        )

    assignments = ", ".join(f"{quote(name)} = EXCLUDED.{quote(name)}" for name in updatable)
    statement = (
        f"INSERT INTO {target} ({columns}) SELECT {columns} FROM gantry_staging "
        f"ON CONFLICT ({key_columns}) DO UPDATE SET {assignments}"
    )
    if snapshot_lsn is None:
        return _counted(statement)
    return _counted(f"{statement} WHERE {target}.source_lsn <= {int(snapshot_lsn)}")


COMMIT_MARKER = "gantry-commit"


def _counted(statement: str) -> str:
    """Wrap a merge so it reports what it did.

    The executor needs a `CommitResult` before a checkpoint may advance, and a
    container only reports an exit code. So the script says so itself, on one
    line, in the same terms the in-process relay derived: `xmax = 0`
    distinguishes an insert from an update, and rows the statement declined to
    touch never come back from RETURNING, so staged-minus-affected is the
    unchanged count.
    """
    return (
        f"WITH merged AS ({statement} RETURNING (xmax = 0) AS inserted) "
        f"SELECT '{COMMIT_MARKER} ' "
        f"|| count(*) FILTER (WHERE inserted) || ' ' "
        f"|| count(*) FILTER (WHERE NOT inserted) || ' ' "
        f"|| ((SELECT count(*) FROM gantry_staging) - count(*)) FROM merged"
    )


def parse_commit(output: str, *, committed_at: datetime | None = None) -> CommitResult:
    """Read a job's output into the attestation a checkpoint requires.

    A missing marker is an error rather than a zero result. The script prints
    it as its last act inside the committing transaction, so its absence means
    the merge did not run to completion — and a silent zero there would let a
    checkpoint advance over work that never happened.
    """
    for line in reversed(output.splitlines()):
        line = line.strip()
        if not line.startswith(COMMIT_MARKER):
            continue
        parts = line.split()
        if len(parts) != 4:
            raise ValueError(f"malformed commit line: {line!r}")
        inserted, updated, unchanged = (int(part) for part in parts[1:])
        return CommitResult(
            rows_inserted=inserted,
            rows_updated=updated,
            rows_unchanged=unchanged,
            committed_at=committed_at or datetime.now(UTC),
        )
    raise ValueError(f"no {COMMIT_MARKER!r} line in the job's output; the merge did not complete")
